### ISSUE TITLE
Add note to the docs about allowing dev versions.

### ISSUE THREAD

**Issue by oalders** [tokuhirom/OrePAN2#22]
In order to inject TRIAL versions, I've needed to add the following to my code.  It would be nice if there were a note about this in the docs somewhere and probably a command line option to do this.

```perl
use Parse::PMFile;
local $Parse::PMFile::ALLOW_DEV_VERSION = 1;
```

**Comment by RsrchBoy** [comment]
This just bit me, too. :\

**Comment by oalders** [comment]
I'm just poking around at this and it's really not clear to me how this is supposed to work.  I've opened a ticket here.  https://rt.cpan.org/Ticket/Display.html?id=103833  AFAICT, OrePAN2 will only not index a dev release if there is no META provides and if the versions of the modules contained have underscores.

By default, we probably shouldn't index files which contain -TRIAL or releases which have an underscore in their version, regardless of whether there is a provides field.

It feels like we're already quite permissive and it's just some TRIAL releases that we're not indexing, which is pretty confusing.
