### ISSUE TITLE
Sort packages case insensitively

### ISSUE THREAD

**Issue by miyagawa** [tokuhirom/OrePAN2#38]
I haven't tested but OrePAN seems to generate 02packages by sorting the package names case sensitively. https://github.com/tokuhirom/OrePAN2/blob/master/lib/OrePAN2/Index.pm#L58

PAUSE does it case insensitively, and OrePAN should do it the same.
https://github.com/andk/pause/blob/master/lib/PAUSE/mldistwatch.pm#L635

**Comment by oalders** [comment]
Good catch. I'll fix and release in the next day or so.
