### ISSUE TITLE
Can't locate t/Util.pm in @INC

### ISSUE THREAD

**Issue by biafra** [tokuhirom/OrePAN2#52]
Hi,

It doesn't do the tests by default:

(...)
cp script/orepan2-indexer blib/script/orepan2-indexer
cp script/orepan2-inject blib/script/orepan2-inject
t/00_compile.t ....... ok
Can't locate t/Util.pm in @INC (you may need to install the t::Util module) (@INC contains:
(...)

Adding '.' to PERL5LIB it works.

**Comment by oalders** [comment]
Thanks for the report @biafra. It looks like this was fixed in 0ce72cf700069 but never released.  I'll release a new version today.

**Comment by oalders** [comment]
0.47 has now been released.

**Comment by biafra** [comment]
Great. Thank you!
